Geo paritioning stress
yugabyte/yb-stress-test pull request #25
Opened 2021-12-08 11:53 UTC by pilshchikov

2021-12-09 19:19 UTC, qvad requested changes

2021-12-09 19:19 UTC, qvad commented on tools/sample-app/src/main/java/com/yugabyte/sample/apps/SqlGeoTransactions.java
> +        stmt.append("COMMIT;");
as far as I understand the code - safe points are only exists on client side here, because we sent only String with bunch of operations.
probably correct way to use safe points is to commit statement in every place where you have stmt.append

2021-12-10 10:32 UTC, pilshchikov commented on tools/sample-app/src/main/java/com/yugabyte/sample/apps/SqlTransactions.java
> +    static final Logger LOG = Logger.getLogger(SqlTransactions.class);
fixed

2021-12-10 10:33 UTC, pilshchikov commented on tools/sample-app/src/main/java/com/yugabyte/sample/apps/SqlGeoTransactions.java
> +        stmt.append("COMMIT;");
Every commit is ending transaction. Savepoints can't rollback on state inside previous committed transaction.

2021-12-22 09:54 UTC, qvad approved these changes

2021-12-22 14:56 UTC, merged