[WIP] Follower reads tests
yugabyte/yb-stress-test pull request #8
Opened 2021-11-18 06:04 UTC by qvad

2021-11-18 06:04 UTC, qvad commented on src/configs/artifacts.conf
> -    url = "https://github.com/yugabyte/yb-stress-test/releases/download/sa_{sample-app-tool}/yb-sample-apps-{sample-app-tool}.jar"
will fix that

2021-11-23 13:14 UTC, pilshchikov requested changes

2021-11-23 13:14 UTC, pilshchikov commented on src/apps/yugabyte/yugabyte_nemesis.py
> +        self.sudo_ssh: Connection = Connection([ConnectionConfig(host, sudo_access=True) for host in config.server_hosts], self.logger)
```suggestion
        server_hosts = []
        for host in config.server_hosts:
            host['username'] = host.get('sudo_username', host['username'])
            server_hosts.append(ConnectionConfig(host))

        self.sudo_ssh: Connection = Connection(server_hosts, self.logger)
```
And no need for `sudo_access` property

2021-11-23 13:14 UTC, pilshchikov commented on tools/sample-app/src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
> +    if (commandLine.hasOption("follower_reads")) {
We should print that `follower_reads` is enabled in log

2021-11-23 13:14 UTC, pilshchikov commented on src/suites/follower_reads/test_sample_apps.py
> +        self.reporter.end_step(f"Node has been restarted {restarted_nodes}", True)
```suggestion
        step_id = self.reporter.start_step("Restarting random node")
        restarted_nodes = self.yb_nemesis.restart_random_node()
        self.logger.info(f"Node has been restarted {restarted_nodes}")
        self.reporter.end_step(step_id, True)
```

2021-11-23 13:14 UTC, pilshchikov commented on src/suites/follower_reads/test_sample_apps.py
> +    def wait_steps(self, timeout_sec: int, with_restarts=False):
Needs to add some assertions on failed steps
If some workload is ended badly then failed the test
You can do that right it there or at the end of the run

2021-11-23 13:14 UTC, pilshchikov commented on src/suites/follower_reads/test_sample_apps.py
> +class SingleWorkloadSuite(AbstractStressSuite):
Please describe how to run universe for this test, what topology, what g-flags and so on

2021-11-25 15:48 UTC, pilshchikov approved these changes

2021-11-25 15:48 UTC, merged